/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Victus
 */
public class AndraAgent extends javax.swing.JFrame {

    private InfDB idb;
    private int agentId;

    /**
     * Creates new form AndraAlien
     */
    public AndraAgent(InfDB idb, int agentId) {
        initComponents();
        this.idb = idb;
        this.agentId = agentId;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bilden = new javax.swing.JLabel();
        AgentIDtxt = new javax.swing.JTextField();
        Namntxt = new javax.swing.JTextField();
        Teltxt = new javax.swing.JTextField();
        Registreringsdatum = new javax.swing.JLabel();
        AlienID = new javax.swing.JLabel();
        Lösenord = new javax.swing.JLabel();
        Namn = new javax.swing.JLabel();
        AnsvarigAgentID = new javax.swing.JLabel();
        Omradetext = new javax.swing.JTextField();
        AnsDattxt = new javax.swing.JTextField();
        Andratext = new javax.swing.JButton();
        GaTillbakaKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Bilden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MIBprojekt/Ikoner/men-in-black-2-logo.png"))); // NOI18N

        AgentIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentIDtxtActionPerformed(evt);
            }
        });

        Namntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamntxtActionPerformed(evt);
            }
        });

        Teltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeltxtActionPerformed(evt);
            }
        });

        Registreringsdatum.setForeground(new java.awt.Color(255, 255, 255));
        Registreringsdatum.setText("Namn");

        AlienID.setForeground(new java.awt.Color(255, 255, 255));
        AlienID.setText("AgentID");

        Lösenord.setForeground(new java.awt.Color(255, 255, 255));
        Lösenord.setText("Telefon");

        Namn.setForeground(new java.awt.Color(255, 255, 255));
        Namn.setText("Anställningsdatum");

        AnsvarigAgentID.setForeground(new java.awt.Color(255, 255, 255));
        AnsvarigAgentID.setText("Område");

        Omradetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmradetextActionPerformed(evt);
            }
        });

        AnsDattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsDattxtActionPerformed(evt);
            }
        });

        Andratext.setText("Ändra");
        Andratext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndratextActionPerformed(evt);
            }
        });

        GaTillbakaKnapp.setText("Gå tillbaka");
        GaTillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaTillbakaKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bilden, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Omradetext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsvarigAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Registreringsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Andratext, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Namntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Teltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(GaTillbakaKnapp)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnsDattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Bilden, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlienID)
                    .addComponent(Registreringsdatum)
                    .addComponent(Lösenord)
                    .addComponent(Namn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Namntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Teltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsDattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(AnsvarigAgentID)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Omradetext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Andratext, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GaTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamntxtActionPerformed
      
    }//GEN-LAST:event_NamntxtActionPerformed

    private void TeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeltxtActionPerformed
       
    }//GEN-LAST:event_TeltxtActionPerformed

    private void OmradetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmradetextActionPerformed
        
    }//GEN-LAST:event_OmradetextActionPerformed

    /**
     * Denna metod används för att uppdatera informationen för en specifik
     * agent. Metoden hämtar de nya värdena för agentens attribut från
     * textkomponenterna i användargränssnittet. En SQL-uppdateringsfråga byggs
     * upp dynamiskt baserat på de fält som har ändrats. Om inga fält har
     * ändrats visas en bekräftelse att det inte finns några fält att uppdatera.
     * Annars utförs databasuppdateringen för att uppdatera agentens information
     * baserat på dess Agent_ID. Om uppdateringen lyckas visas en bekräftelse
     * att agentens information har uppdaterats, och textkomponenterna rensas
     * för att förbereda för nya ändringar. Om det uppstår något fel under
     * databasåtkomst visas ett generellt felmeddelande.
     */
    private void AndratextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndratextActionPerformed
        // Hämta värden från textkomponenter
        String AID = AgentIDtxt.getText();
        String namn = Namntxt.getText();
        String Tel = Teltxt.getText();
        String AnsDat = AnsDattxt.getText();
        String Omrade = Omradetext.getText();

        StringBuilder uppdateraFalt = new StringBuilder("UPDATE agent SET ");

        boolean faltUppdaterade = false;

        // Kontrollera om namnet har ändrats
        if (!namn.isEmpty()) {
            uppdateraFalt.append("Namn = '").append(namn).append("'");
            faltUppdaterade = true;
        }
        // Kontrollera om telefonnumret har ändrats
        if (!Tel.isEmpty()) {
            if (faltUppdaterade) {
                uppdateraFalt.append(", ");
            }
            uppdateraFalt.append("Telefon = '").append(Tel).append("'");
            faltUppdaterade = true;
        }
        // Kontrollera om anställningsdatumet har ändrats
        if (!AnsDat.isEmpty()) {
            if (faltUppdaterade) {
                uppdateraFalt.append(", ");
            }
            uppdateraFalt.append("Anstallningsdatum = '").append(AnsDat).append("'");
            faltUppdaterade = true;
        }
        // Kontrollera om området har ändrats
        if (!Omrade.isEmpty()) {
            if (faltUppdaterade) {
                uppdateraFalt.append(", ");
            }
            uppdateraFalt.append("Omrade = '").append(Omrade).append("'");
            faltUppdaterade = true;
        }
        // Kontrollera om några fält har ändrats
        if (!faltUppdaterade) {
            JOptionPane.showMessageDialog(this, "Inga fält att Uppdatera");
            return;
        }

        // Bygg upp uppdateringsfrågan baserat på ändrade fält och Agent_ID
        uppdateraFalt.append(" WHERE Agent_ID = '").append(AID).append("'");
        String fraga = uppdateraFalt.toString();

        System.out.println("SQL Fråga: " + fraga);

        try {
            
            // Utför databasuppdateringen
            idb.update(fraga);
            JOptionPane.showMessageDialog(null, "Agentens Information är nu uppdaterad!");
            AgentIDtxt.setText("");
            Namntxt.setText("");
            Teltxt.setText("");
            AnsDattxt.setText("");
            Omradetext.setText("");
            AgentIDtxt.requestFocus();

        } catch (InfException ex) {
            Logger.getLogger(AndraAgent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Något gick fel!");

        }
    }//GEN-LAST:event_AndratextActionPerformed

    private void GaTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaTillbakaKnappActionPerformed
        AdminMeny AM = new AdminMeny(idb, agentId);
        AM.setVisible(true);

        dispose();
    }//GEN-LAST:event_GaTillbakaKnappActionPerformed

    private void AnsDattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsDattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnsDattxtActionPerformed

    private void AgentIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgentIDtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgentIDtxt;
    private javax.swing.JLabel AlienID;
    private javax.swing.JButton Andratext;
    private javax.swing.JTextField AnsDattxt;
    private javax.swing.JLabel AnsvarigAgentID;
    private javax.swing.JLabel Bilden;
    private javax.swing.JButton GaTillbakaKnapp;
    private javax.swing.JLabel Lösenord;
    private javax.swing.JLabel Namn;
    private javax.swing.JTextField Namntxt;
    private javax.swing.JTextField Omradetext;
    private javax.swing.JLabel Registreringsdatum;
    private javax.swing.JTextField Teltxt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
