/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Victus
 */
public class NyAlien extends javax.swing.JFrame {

    private InfDB idb;
    private int agentId;

    /**
     * Creates new form NyAlien
     */
    public NyAlien(InfDB idb, int agentId) {
        initComponents();
        this.idb = idb;
        this.agentId = agentId;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bilden = new javax.swing.JLabel();
        Eposttext = new javax.swing.JTextField();
        AlienIDtext = new javax.swing.JTextField();
        Registreringsdatumtext = new javax.swing.JTextField();
        Losenordtext = new javax.swing.JTextField();
        Registreringsdatum = new javax.swing.JLabel();
        AlienID = new javax.swing.JLabel();
        Epost = new javax.swing.JLabel();
        Lösenord = new javax.swing.JLabel();
        Namn = new javax.swing.JLabel();
        Telefon = new javax.swing.JLabel();
        Plats = new javax.swing.JLabel();
        AnsvarigAgentID = new javax.swing.JLabel();
        AnsvarigAgentIDtext = new javax.swing.JTextField();
        Platstext = new javax.swing.JTextField();
        Rastext = new javax.swing.JTextField();
        Namntext = new javax.swing.JTextField();
        LäggTillAlienKnapp = new javax.swing.JButton();
        GaTillbakaKnapp = new javax.swing.JButton();
        Telefontext1 = new javax.swing.JTextField();
        Ras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Bilden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MIBprojekt/Ikoner/men-in-black-2-logo.png"))); // NOI18N

        Eposttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EposttextActionPerformed(evt);
            }
        });

        Registreringsdatumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreringsdatumtextActionPerformed(evt);
            }
        });

        Losenordtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LosenordtextActionPerformed(evt);
            }
        });

        Registreringsdatum.setForeground(new java.awt.Color(255, 255, 255));
        Registreringsdatum.setText("Registreringsdatum");

        AlienID.setForeground(new java.awt.Color(255, 255, 255));
        AlienID.setText("AlienID");

        Epost.setForeground(new java.awt.Color(255, 255, 255));
        Epost.setText("Epost");

        Lösenord.setForeground(new java.awt.Color(255, 255, 255));
        Lösenord.setText("Lösenord");

        Namn.setForeground(new java.awt.Color(255, 255, 255));
        Namn.setText("Namn");

        Telefon.setForeground(new java.awt.Color(255, 255, 255));
        Telefon.setText("Telefon");

        Plats.setForeground(new java.awt.Color(255, 255, 255));
        Plats.setText("Plats");

        AnsvarigAgentID.setForeground(new java.awt.Color(255, 255, 255));
        AnsvarigAgentID.setText("Ansvarig AgentID");

        AnsvarigAgentIDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsvarigAgentIDtextActionPerformed(evt);
            }
        });

        LäggTillAlienKnapp.setText("Lägg till Alien");
        LäggTillAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LäggTillAlienKnappActionPerformed(evt);
            }
        });

        GaTillbakaKnapp.setText("Gå tillbaka");
        GaTillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaTillbakaKnappActionPerformed(evt);
            }
        });

        Ras.setForeground(new java.awt.Color(255, 255, 255));
        Ras.setText("Ras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Namntext)
                            .addComponent(Namn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Telefontext1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Platstext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AnsvarigAgentIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Plats, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AnsvarigAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LäggTillAlienKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AlienIDtext)
                            .addComponent(AlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Registreringsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(Registreringsdatumtext, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Eposttext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Losenordtext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(Epost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bilden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ras, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rastext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(377, 377, 377))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GaTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Bilden, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registreringsdatum)
                    .addComponent(AlienID)
                    .addComponent(Epost)
                    .addComponent(Lösenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eposttext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlienIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registreringsdatumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Losenordtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefon)
                    .addComponent(Namn)
                    .addComponent(Plats)
                    .addComponent(AnsvarigAgentID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Platstext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Namntext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsvarigAgentIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefontext1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Ras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rastext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LäggTillAlienKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GaTillbakaKnapp)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LosenordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LosenordtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LosenordtextActionPerformed

    private void AnsvarigAgentIDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsvarigAgentIDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnsvarigAgentIDtextActionPerformed

    private void RegistreringsdatumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreringsdatumtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistreringsdatumtextActionPerformed

    private void EposttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EposttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EposttextActionPerformed

    //LäggTillAlienKnapp 
    private void LäggTillAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LäggTillAlienKnappActionPerformed
        // TODO add your handling code here:

        laggTillNyAlien();

    }//GEN-LAST:event_LäggTillAlienKnappActionPerformed

    /**
     *
     * Denna metod används för att lägga till en ny alien i databasen baserat på
     * de angivna värdena i användargränssnittet. Metoden hämtar informationen
     * från olika textkomponenter och utför sedan en SQL-insättning för att
     * lägga till den nya alienen i databasen. Om insättningen lyckas visas en
     * bekräftelse att den nya alienen har lagts till, och textkomponenterna
     * rensas för att förbereda för en ny alien. Om det uppstår något fel under
     * databasåtkomst, loggas felet och ett felmeddelande visas.
     */
    
    private void laggTillNyAlien() {
        String AID = AlienIDtext.getText();
        String RegDatum = Registreringsdatumtext.getText();
        String epost = Eposttext.getText();
        String Losen = Losenordtext.getText();
        String namn = Namntext.getText();
        String telefon = Telefontext1.getText();
        String plats = Platstext.getText();
        String ansvarigAgentID = AnsvarigAgentIDtext.getText();
        String ras = Rastext.getText();

        try {
            String fraga = "INSERT INTO alien (Alien_ID, Registreringsdatum, Epost, Losenord, Namn, Telefon, Plats, Ansvarig_Agent) VALUES ('" + AID + "', '" + RegDatum + "', '" + epost + "', '" + Losen + "', '" + namn + "', '" + telefon + "', '" + plats + "', '" + ansvarigAgentID + "')";
            idb.insert(fraga);
            String TilldelaRas = "INSERT INTO " + ras + " (Alien_ID) VALUES ('" + AID + "')";
            idb.insert(TilldelaRas);

            /* String TilldelaRas = "";

           } else if ("worm".equals(ras)) {
                TilldelaRas = "INSERT INTO worm (Alien_ID) VALUES (1)";
            } else if ("boglodite".equals(ras)) {
                TilldelaRas = "INSERT INTO boglodite (Alien_ID) VALUES (1)";
            }

            if (!TilldelaRas.isEmpty()) {
                idb.insert(TilldelaRas);
            }*/
            JOptionPane.showMessageDialog(this, "Ny Alien har lagts till!");
            AlienIDtext.setText("");
            Registreringsdatumtext.setText("");
            Eposttext.setText("");
            Losenordtext.setText("");
            Namntext.setText("");
            Telefontext1.setText("");
            Platstext.setText("");
            AnsvarigAgentIDtext.setText("");
            AlienIDtext.requestFocus();
        } catch (InfException ex) {
            Logger.getLogger(NyAlien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Finns redan en Alien med detta ID");
        }

    }
    private void GaTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaTillbakaKnappActionPerformed
        AgentMeny AM = new AgentMeny(idb, agentId);
        AM.setVisible(true);

        dispose();
    }//GEN-LAST:event_GaTillbakaKnappActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlienID;
    private javax.swing.JTextField AlienIDtext;
    private javax.swing.JLabel AnsvarigAgentID;
    private javax.swing.JTextField AnsvarigAgentIDtext;
    private javax.swing.JLabel Bilden;
    private javax.swing.JLabel Epost;
    private javax.swing.JTextField Eposttext;
    private javax.swing.JButton GaTillbakaKnapp;
    private javax.swing.JTextField Losenordtext;
    private javax.swing.JButton LäggTillAlienKnapp;
    private javax.swing.JLabel Lösenord;
    private javax.swing.JLabel Namn;
    private javax.swing.JTextField Namntext;
    private javax.swing.JLabel Plats;
    private javax.swing.JTextField Platstext;
    private javax.swing.JLabel Ras;
    private javax.swing.JTextField Rastext;
    private javax.swing.JLabel Registreringsdatum;
    private javax.swing.JTextField Registreringsdatumtext;
    private javax.swing.JLabel Telefon;
    private javax.swing.JTextField Telefontext1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
